services:
  db:
    image: postgres:16-alpine
    container_name: procurement_mvp_db
    environment:
      POSTGRES_DB: procurement_mvp
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: workshop
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/workspace/db:ro
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
